package com.example.trackmytrip.ui.theme

import androidx.compose.ui.graphics.Color

val TrackPrimary = Color(0xFF006C67)
val TrackOnPrimary = Color(0xFFFFFFFF)
val TrackPrimaryContainer = Color(0xFFA6F2EA)
val TrackOnPrimaryContainer = Color(0xFF00201E)
val TrackSecondary = Color(0xFF4A6361)
val TrackSecondaryContainer = Color(0xFFCCE8E4)
val TrackTertiary = Color(0xFF835500)
val TrackTertiaryContainer = Color(0xFFFFDEA5)
val TrackSurface = Color(0xFFF5FBF9)
val TrackSurfaceContainer = Color(0xFFE9F1EF)
val TrackSurfaceContainerHigh = Color(0xFFE3EBE9)
val TrackOnSurface = Color(0xFF171D1C)
val TrackOnSurfaceVariant = Color(0xFF3F4947)
val TrackOutline = Color(0xFF6F7977)
val TrackOutlineVariant = Color(0xFFBEC9C6)

val TrackPrimaryDark = Color(0xFF55DBD2)
val TrackOnPrimaryDark = Color(0xFF003734)
val TrackPrimaryContainerDark = Color(0xFF00504C)
val TrackOnPrimaryContainerDark = Color(0xFFA6F2EA)
val TrackSecondaryDark = Color(0xFFB1CCC8)
val TrackSecondaryContainerDark = Color(0xFF334B49)
val TrackTertiaryDark = Color(0xFFFFB951)
val TrackTertiaryContainerDark = Color(0xFF633F00)
val TrackSurfaceDark = Color(0xFF0E1514)
val TrackSurfaceContainerDark = Color(0xFF1A2221)
val TrackSurfaceContainerHighDark = Color(0xFF252D2C)
val TrackOnSurfaceDark = Color(0xFFDEE4E2)
val TrackOnSurfaceVariantDark = Color(0xFFBEC9C6)
val TrackOutlineDark = Color(0xFF899390)
val TrackOutlineVariantDark = Color(0xFF3F4947)
